### ISSUE TITLE
Unable to see video track,and server log: "getBuffer failed, buffer not found"

### ISSUE THREAD

**Issue by ocean2811** [livekit/livekit#1003]
**Describe the bug**
After two members joining,  they can only listen to each other's audio but can't see each other's video

**Server**
- Version:    v1.2.1
- Environment: docker livekit/livekit-server:v1.2.1

**Client**
- https://example.livekit.io/

**To Reproduce**
1. two clients are connected to room

**Expected behavior**
Audio and video are available.

**Screenshots**
![image](https://user-images.githubusercontent.com/30968392/190069031-ae383407-da7b-47ad-9c45-5a3580f43f19.png)

**Additional context**
user1 token:
{"exp":1676020187,"iss":"APIiJfiVb9nv5c7","name":"test_user1","nbf":1663060187,"sub":"test_user1","video":{"room":"test","roomAdmin":true,"roomCreate":true,"roomJoin":true,"roomList":true}}

user2 token:
{"exp":1676027123,"iss":"APIiJfiVb9nv5c7","name":"test_user2","nbf":1663067123,"sub":"test_user2","video":{"room":"test","roomAdmin":true,"roomCreate":true,"roomJoin":true,"roomList":true}}

**Comment by boks1971** [comment]
@ocean2811 Thank you for the report. Can you please attach full server logs?

**Comment by boks1971** [comment]
From the logs, I see `vp9`. VP9 is not a supported codec. That could be the issue. How are you using VP9?

**Comment by ocean2811** [comment]
> 从日志中，我看到`vp9`. VP9 不是受支持的编解码器。这可能是问题所在。你是如何使用 VP9 的？

I just open `https://example.livekit.io` directly in Chrome browser, and enter the server wss address and token

**Comment by ocean2811** [comment]
server log:
[livekit.log](https://github.com/livekit/livekit/files/9563209/livekit.log)

**Comment by ocean2811** [comment]
> From the logs, I see `vp9`. VP9 is not a supported codec. That could be the issue. How are you using VP9?

I just open https://example.livekit.io directly in Chrome browser, and enter the server wss address and token

**Comment by ocean2811** [comment]
I remember that `pion` supports vp9. Does LiveKit not support it?

**Comment by boks1971** [comment]
Can you please share your server config? Especially the `enabled_codecs` part? Guessing you have VP9 enabled in it.

We are not planning support for VP9. We will be supporting AV1 when it is a supported codecs on browsers.

**Comment by ocean2811** [comment]
Yes, I enabled vp9:

```yaml
port: 7880

rtc:
  port_range_start: 50000
  port_range_end: 51000
  tcp_port: 7881
  use_external_ip: false
  node_ip: 115.13.119.9
  use_ice_lite: true
  congestion_control:
    enabled: true
    allow_pause: true
    send_side_bandwidth_estimation: false

keys:
  APIiXXXXX: xxxxxxx

logging:
  level: info
  pion_level: error


room:
  auto_create: true
  empty_timeout: 60
  max_participants: 50
  enabled_codecs:
    - mime: audio/opus
    - mime: video/vp9
  enable_remote_unmute: false
  max_metadata_size: 0
```
