### ISSUE TITLE
Error "Could not connect PeerConnection after timeout"

### ISSUE THREAD

**Issue by CaosFR** [livekit/livekit#1060]
Hi,

Since last update I got a error for every client outside my LAN who try to connect to a room a/v of my livekit server (self-host) : "Could not connect PeerConnection after timeout". If I try inside my LAN it's ok (192.168.x.x).
I have try to disable, my UFW, my fail2ban and the firewall of my Internet Box, activate the DMZ. I have make a new fresh install of livekit. I have other service (https) without any problems to connect. All service are NAT forwardings.

Repoduce the error : 
Go to : https://example.livekit.io/ or https://livekit.io/connection-test
LiveKit URL : https://my.hombrew.dns/
Token : Generate with "docker run --rm -v$PWD:/output livekit/generate --local"

=> Ok for me (LAN), error for client (INTERNET).

For information : Old post for the configuration with docker "https://github.com/livekit/livekit/issues/687"

Thanks for any help, I become mad..

Configuration : 
```
cat docker-compose.yaml
version: '3'

services:
  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml --node-ip xxx
    container_name: livekit
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "7881:7881"
      - "7882:7882/udp"
    networks:
      - proxy
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.livekit.entrypoints=web,websecure"
      - "traefik.http.routers.livekit.rule=Host(`xxx.xxx.xxx`)"
      - "traefik.http.routers.livekit.service=livekit"
      - "traefik.http.routers.livekit.tls=true"
      - "traefik.http.routers.livekit.tls.domains[0].main=xxx.xxx.xxx"
      - "traefik.http.routers.livekit.tls.domains[0].sans=*-*.xxx.xxx"
      - "traefik.http.services.livekit.loadbalancer.server.port=7880"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
```

```
cat livekit.yaml
port: 7880
rtc:
    udp_port: 7882
    tcp_port: 7881
    use_external_ip: false
keys:
    XXX: XXX
logging:
    json: false
    level: info
```

```
sudo ufw status
Status: active
To                         Action      From
--                         ------      ----
XXX
7881/tcp                   ALLOW       Anywhere
7882/udp                   ALLOW       Anywhere
XXX
7881/tcp (v6)              ALLOW       Anywhere (v6)
7882/udp (v6)              ALLOW       Anywhere (v6)
```
NAT :
![Capture](https://user-images.githubusercontent.com/37581932/193129631-0a9e9245-e8a4-4fdc-a7da-c8a6e7adc5c6.PNG)
```
Error from https://livekit.io/connection-test
Connecting to signal connection via WebSocket

Connected to server, version 1.2.3.

Establishing WebRTC connection

Warning: ports need to be open on firewall in order to connect.

Error: could not connect after timeout

SKIPPED: Can connect via TURN

Warning: No TURN servers configured.

Can publish audio

Error: could not connect after timeout

Can publish video

Error: could not connect after timeout

Resuming connection after interruption

Warning: could not connect after timeout

Fail
```
Log : [livekit_log.txt](https://github.com/livekit/livekit/files/9678767/livekit_log.txt)
