### ISSUE TITLE
Livekit over version 1.2.3 and public IP on loopback interface - Connection timeout

### ISSUE THREAD

**Issue by nerthazrim** [livekit/livekit#1160]
**Describe the bug**
When a VM has its public IP on the loopback interface, the socket opening on UDP dynamic ports (50000-60000) seems to listen only the non-loopback interfaces.
After version 1.2.3, even with DNAT for the 50000-60000 udp range, clients are getting a connection timeout.
Version 1.2.3 works fine.

**Server**
- Version: [1.2.3]
- Environment: [Proxmox VM running on Debian 11]
- public IP is on the loopback interface, private IP on another interface
**Client**
Any

**To Reproduce**
1. setup DNAT to redirect any traffic coming on PUBLIC_IP:50000-60000 to PRIVATE_IP:50000-60000
2. start livekit-server 1.2.3
3. see clients connecting and using the service smoothly
4. stop livekit
5. upgrade livekit-server to, say most recent version 1.3.1
6. start livekit
7. see clients initially connecting, getting the server version then getting a timeout

**Expected behavior**
Clients should be able to connect in both cases

**Additional information**
I can't change the fact that my public IP is on the loopback interface, my host set ip up that way

---

Does anyone understand why my setup works on 1.2.3 on not on recent versions?
Otherwise, is there any way to force livekit-server to listen on the loopback interface when opening a socket on port UDP:50000-6000 ?

I saw that ticket that would probably solve my issue: https://github.com/livekit/livekit/issues/1111

Thanks!

**Comment by nerthazrim** [comment]
Version 1.2.3 on https://livekit.io/connection-test :
![image](https://user-images.githubusercontent.com/8452948/201328231-29b6df6b-6d85-497a-beee-d545aa6c484d.png)

Version 1.3.1 on https://livekit.io/connection-test :
![image](https://user-images.githubusercontent.com/8452948/201328458-09a22ab8-ad44-481f-baf8-ba3917514535.png)

Everything else remains the same on my configuration

**Comment by cnderrauber** [comment]
can you post your network config and livekit-server config file?

**Comment by nerthazrim** [comment]
Sure!

Here is the network configuration:
```
# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet PUBLIC_IP/32 brd GATEWAY_IP scope global lo
       valid_lft forever preferred_lft forever
    inet6 PUBLIC_IPv6/128 scope global
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether ca:29:cc:36:b8:43 brd ff:ff:ff:ff:ff:ff
    altname enp0s18
    altname ens18
    inet 10.10.1.80/24 brd 10.10.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 PRIVATE_IPv6/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::c829:ccff:fe36:b843/64 scope link
       valid_lft forever preferred_lft forever
```

And the livekit-server config file :

```
# main TCP port for RoomService and RTC endpoint
# for production setups, this port should be placed behind a load balancer with TLS
port: 7880

# when redis is set, LiveKit will automatically operate in a fully distributed fashion
# clients could connect to any node and be routed to the same room
#redis:
  #address: redis.host:6379
  # To require TLS transport
  # use_tls: true
  # db: 0
  # username: myuser
  # password: mypassword
  # To use sentinel remove the address key above and add the following
  # sentinel_master_name: livekit
  # sentinel_addresses:
  # - livekit-redis-node-0.livekit-redis-headless:26379
  # - livekit-redis-node-1.livekit-redis-headless:26379
  # If you use a different set of credentials for sentinel add
  # sentinel_username: user
  # sentinel_password: pass

# WebRTC configuration
rtc:
  # UDP ports to use for client traffic.
  # this port range should be open for inbound traffic on the firewall
  port_range_start: 50000
  port_range_end: 60000
  # when set, LiveKit enable WebRTC ICE over TCP when UDP isn't available
  # this port *cannot* be behind load balancer or TLS, and must be exposed on the node
  # WebRTC transports are encrypted and do not require additional encryption
  # only 80/443 on public IP are allowed if less than 1024
  tcp_port: 7881
  # when set to true, attempts to discover the host's public IP via STUN
  # this is useful for cloud environments such as AWS & Google where hosts have an internal IP
  # that maps to an external one
  #use_external_ip: yes
  # when set to true, server will use a lite ice agent, that will speed up ice connection, but
  # might cause connect issue if server running behind NAT.
  # use_ice_lite: true
  # when set, LiveKit will attempt to use a UDP mux so all UDP traffic goes through
  # a single port. This simplifies deployment, but mux will become an overhead for
  # highly trafficked deployments.
  # port_range_start & end must not be set for this config to take effect
  # udp_port: 7882
  # optional settings
  # # number of packets to buffer in the SFU, defaults to 500
  # packet_buffer_size: 500
  # # optional STUN servers for LiveKit clients to use. Clients will be configured to use these STUN servers automatically.
  # # by default LiveKit clients use Google's public STUN servers
  # stun_servers:
  #   - server1
  # # optional TURN servers for clients. This isn't necessary if using embedded TURN server (see below).
  # turn_servers:
  #   - host: myhost.com
  #     port: 443
  #     # tls, tcp, or udp
  #     protocol: tls
  #     username: ""
  #     credential: ""
  # # allows LiveKit to monitor congestion when sending streams and automatically
  # # manage bandwidth utilization to avoid congestion/loss. Enabled by default
  # congestion_control:
  #   enabled: true
  #   # in the unlikely event of highly congested networks, SFU may choose to pause some tracks
  #   # in order to allow others to stream smoothly. You can disable this behavior here
  #   allow_pause: true
  # # minimum amount of time between pli/fir rtcp packets being sent to an individual
  # # producer. Increasing these times can lead to longer black screens when new participants join,
  # # while reducing them can lead to higher stream bitrate.
  # pli_throttle:
  #   low_quality: 500ms
  #   mid_quality: 1s
  #   high_quality: 1s
  # # network interface filter. If the machine has more than one network interface and you'd like it to use or skip specific interfaces
  # # both inclusion and exclusion filters can be used together. If neither is defined (default), all interfaces on the machine will be used.
  # # If both of them are set, then only interfaces that satisfy both filters will be used.
  # # If an interface is present in both lists, include takes precedence.
  # interfaces:
  #   includes:
  #     - en0
  #   excludes:
  #     - docker0

# when enabled, LiveKit will expose prometheus metrics on :6789/metrics
# prometheus_port: 6789

# API key / secret pairs.
# Keys are used for JWT authentication, server APIs would require a keypair in order to generate access tokens
# and make calls to the server
keys:
  KEY: PASS

# Logging config
# logging:
#   # log level, valid values: debug, info, warning, error
#   level: info
#   # log level for pion, default error
#   pion_level: error
#   # when set to true, emit json fields
#   json: false
#   # for production setups, enables sampling algorithm
#   # https://github.com/uber-go/zap/blob/master/FAQ.md#why-sample-application-logs
#   sample: false


# Default room config
# Each room created will inherit these settings. If rooms are created explicitly with CreateRoom, they will take
# precedence over defaults
# room:
#   # allow rooms to be automatically created when participants join, defaults to true
#   # auto_create: false
#   # number of seconds to leave a room open when it's empty
#   empty_timeout: 300
#   # limit number of participants that can be in a room, 0 for no limit
#   max_participants: 0
#   # only accept specific codecs for clients publishing to this room
#   # this is useful to standardize codecs across clients
#   # other supported codecs are video/h264, video/vp9
#   enabled_codecs:
#     - mime: audio/opus
#     - mime: video/vp8
#   # allow tracks to be unmuted remotely, defaults to false
#   # tracks can always be muted from the Room Service APIs
#   enable_remote_unmute: true
#   # limit size of room and participant's metadata, 0 for no limit
#   max_metadata_size: 0

# Webhooks
# when configured, LiveKit notifies your URL handler with room events
# webhook:
#   # the API key to use in order to sign the message
#   # this must match one of the keys LiveKit is configured with
#   api_key: <api_key>
#   # list of URLs to be notified of room events
#   urls:
#     - https://your-host.com/handler

# customize audio level sensitivity
# audio:
#   # minimum level to be considered active, 0-127, where 0 is loudest
#   # defaults to 30
#   active_level: 30
#   # percentile to measure, a participant is considered active if it has exceeded the
#   # ActiveLevel more than MinPercentile% of the time
#   # defaults to 40
#   min_percentile: 40
#   # frequency in ms to notify changes to clients, defaults to 500
#   update_interval: 500
#   # to prevent speaker updates from too jumpy, smooth out values over N samples
#   smooth_intervals: 4

# turn server
# turn:
#   # Uses TLS. Requires cert and key pem files by either:
#   # - using turn.secretName if deploying with our helm chart, or
#   # - setting LIVEKIT_TURN_CERT and LIVEKIT_TURN_KEY env vars with file locations, or
#   # - using cert_file and key_file below
#   # defaults to false
#   enabled: false
#   # defaults to 3478 - recommended to 443 if not running HTTP3/QUIC server
#   # only 53/80/443 are allowed if less than 1024
#   udp_port: 3478
#   # defaults to 5349 - if not using a load balancer, this must be set to 443
#   tls_port: 5349
#   # set UDP port range for TURN relay to connect to LiveKit SFU, by default it uses a any available port
#   relay_range_start: 1024
#   relay_range_end: 30000
#   # set external_tl to true if using a L4 load balancer to terminate TLS. when enabled,
#   # LiveKit expects unencrypted traffic on tls_port, and still advertise tls_port as a TURN/TLS candidate.
#   external_tls: true
#   # needs to match tls cert domain
#   domain: turn.myhost.com
#   # optional (set only if not using external TLS termination)
#   # cert_file: /path/to/cert.pem
#   # key_file: /path/to/key.pem

# ingress server
# ingress:
#   # Prefix used to generate RTMP URLs for RTMP ingress.
#   # The stream_key will be appended to this base and returned as part of the
#   # ingress info
#   rtmp_base_url: "rtmp://my.domain.com/live"

# Region of the current node. Required if using regionaware node selector
# region: us-west-2

# # node selector
# node_selector:
#   # default: any. valid values: any, sysload, cpuload, regionaware
#   kind: sysload
#   # priority used for selection of node when multiple are available
#   # default: random. valid values: random, sysload, cpuload, rooms, clients, tracks, bytespersec
#   sort_by: sysload
#   # used in sysload and regionaware
#   # do not assign room to node if load per CPU exceeds sysload_limit
#   sysload_limit: 0.7
#   # used in regionaware
#   # list of regions and their lat/lon coordinates
#   regions:
#     - name: us-west-2
#       lat: 44.19434095976287
#       lon: -123.0674908379146

# # node limits
# # set to -1 to disable a limit
# limit:
#   # defaults to 400 tracks in & out per CPU, up to 8000
#   num_tracks: -1
#   # defaults to 1 GB/s, or just under 10 Gbps
#   bytes_per_sec: 1_000_000_000
```
