### ISSUE TITLE
Address not associated with the desired network interface. Could not connect PeerConnection after timeout.

### ISSUE THREAD

**Issue by burzomir** [livekit/livekit#1232]
One of participants is able to connect to a room, start sharing his tracks but then immediately the connection breaks.
The issue was first observed on Firefox but is also confirmed on Chrome. Rarely, if participant doesn't try to connect for some time, he'll be able to connect once, but after refreshing browser's window, the issue occurs again.

**Server**
- Version: [1.2.3, 1.3, custom docker image from latest LiveKit main branch]
- Environment: [Docker]
```
port: 7880
rtc:
    tcp_port: 7881
    port_range_start: 50000
    port_range_end: 60000
    use_external_ip: true
    
    # https://github.com/livekit/livekit/issues/1216#issuecomment-1345151953
    ips:
        excludes:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16

redis:
    address: localhost:6379
    username: ""
    password: ""
    db: 0
turn:
    enabled: true
    domain: livekit-turns.mycompany.com
    cert_file: ""
    key_file: ""
    tls_port: 5349
    udp_port: 443
    external_tls: true
```

**Client**
- SDK: [js]
- Version: [1.5.0]

**To Reproduce**
1. Participant connects to a room,
2. Participant publishes his camera track,
3. Participant can only see himself, other participants can see him,
4. Participant sees error in the browser's console `Could not connect PeerConnection after timeout.`
5. Participant sees error in webrtc internal just after connecting `Address not associated with the desired network interface.` Then connection breaks.

<img width="764" alt="image" src="https://user-images.githubusercontent.com/13577810/208093307-1987d9ce-cfa2-453b-ba84-ed3da6bbe282.png">

Server/browser logs, webrtc internals attached in the following file

[Issue attachments.zip](https://github.com/livekit/livekit/files/10245550/Issue.attachments.zip)

**Comment by nkonev** [comment]
I also have same issue.
And it disappears after the tab reload.
Not very helpful message still, but I will try to capture the logs when it will appear

**Comment by davidzhao** [comment]
@cnderrauber the fact that the participant couldn't connect further could be due to interaction between forceTCP and use of TURN.

not sure why the participant becomes disconnected in the first place though. we should investigate.

**Comment by cnderrauber** [comment]
@burzomir can you remove the `exclude` section in your config and try again? I see the turn address 192.168.0.x, it will not connect to server through this ip if it is excluded.

**Comment by nkonev** [comment]
Right now just experienced the same symptoms(one participant isn't able to see video tracks of other participant - e. g. the first sees only themself and the second sees both), but logs don't contain "Address not associated..." message

livekit 1.2.4
[livekit-log.txt](https://github.com/livekit/livekit/files/10307071/livekit-log.txt)

```
port: 7880
rtc:
    #node_ip: 92.53.64.83
    udp_port: 7882
    #tcp_port: 7881
    tcp_port: 0
    use_external_ip: true
    #use_ice_lite: true
    use_ice_lite: false
    #port_range_start: 35200
    #port_range_end: 35400
    #force_tcp: true
    allow_tcp_fallback: false

#room:
#    enabled_codecs:
#        - mime: audio/opus
#        - mime: video/h264

turn:
    enabled: true
    udp_port: 3478

redis:
    address: redis:6379
    username: ""
    password: ""
    db: 2
keys:
    APIz****: KEU***
logging:
  json: false
  level: info

webhook:
  api_key: 'APIz****'
  urls:
    - 'http://video:1237/internal/livekit-webhook'
```

```
  livekit:
    #image: livekit/livekit-server:v1.2.4
    image: livekit/livekit-server:v1.2.5
    #image: nkonev/livekit:v1.2.5-nkonev
    command: --config /etc/livekit.yaml
    volumes:
      - ./livekit/livekit.yaml:/etc/livekit.yaml
    networks:
      backend:
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.livekit-service.loadbalancer.server.port=7880"
        - "traefik.http.routers.livekit-router.rule=PathPrefix(`/api/livekit`)"
        - "traefik.http.routers.livekit-router.entrypoints=http"
        - "traefik.http.middlewares.livekit-stripprefix-middleware.stripprefix.prefixes=/api/livekit"
        - "traefik.http.routers.livekit-router.middlewares=auth-middleware@file,livekit-stripprefix-middleware,retry-middleware@file"
    ports:
      # turn udp port
      - target: 3478
        published: 3478
        protocol: udp
        mode: host

      # turn tls port
#      - target: 5349
#        published: 5349
#        protocol: tcp
#        mode: host

      # webrtc udp port
      - target: 7882
        published: 7882
        protocol: udp
        mode: host

      # webrtc tcp port
#      - target: 7881
#        published: 7881
#        protocol: tcp
#        mode: host

    logging:
      driver: "journald"
      options:
        tag: chat-livekit

```
