### ISSUE TITLE
Firefox isn't working in 1.3.2

### ISSUE THREAD

**Issue by nkonev** [livekit/livekit#1263]
**Describe the bug**
Context: [here](https://github.com/livekit/livekit/issues/1143) I wrote the working setup for Firefox with livekit-server 1.2.5 with disabling ice lite.

[Here](https://github.com/livekit/livekit/issues/1216) is an (most likely the same) issue with Firefox. [Here](https://github.com/livekit/livekit/pull/1226) is fix for it.

**Server**
- Version: 1.3.2
- Environment: docker swarm, centos 7

```livekit.yaml
port: 7880
rtc:
    udp_port: 7882
    #tcp_port: 7881
    tcp_port: 0
    use_external_ip: true
    #use_ice_lite: true
    use_ice_lite: false
    #port_range_start: 35200
    #port_range_end: 35400
    #force_tcp: true
    allow_tcp_fallback: false
#room:
#    enabled_codecs:
#        - mime: audio/opus
#        - mime: video/h264

turn:
    enabled: true
    udp_port: 3478
```

```docker-compose-infra.yaml
    image: livekit/livekit-server:v1.3.2
    ...
    ports:
      # turn udp port
      - target: 3478
        published: 3478
        protocol: udp
        mode: host

      # turn tls port
#      - target: 5349
#        published: 5349
#        protocol: tcp
#        mode: host

      # webrtc udp port
      - target: 7882
        published: 7882
        protocol: udp
        mode: host

      # webrtc tcp port
#      - target: 7881
#        published: 7881
#        protocol: tcp
#        mode: host
```

log is attached (132.txt)
[132.txt](https://github.com/livekit/livekit/files/10308137/132.txt)

**Client**
- SDK: JavaScript "livekit-client": "1.6.0",

So I see that existing setup made for 1.2.5 is not working for 1.3.2

**To Reproduce**
Just connect from Firefox Linux 106.0.4 to the room

After some time (5-40 seconds it disconnects and tries to reconnect)

**Expected behavior**
Not to reconnect

**Additional context**
I made the custom build with disabled patch https://github.com/livekit/livekit/pull/1226/files#diff-5c2446a24723d589881637c71008cafa7e3c16159fee094a8ab028eb2a5638bcR261
```pkg/rtc/clientinfo.go
func (c ClientInfo) SupportPrflxOverRelay() bool {
	return true
}
```

and it works again.

My thoughts:
Having this long-term weird Firefox behavior, which is not working for some cases -
to make this patch configurable, to make a config option to disable this firefox-related behavior - something like
```
rtc:
  firefox_prflx_over_relay_patch: false
```
I know that it is not the best solution, but it will fix my case.

---
Here is `about:webrtc` from the different attempt - becasue of this timestamps are different
[aboutWebrtc.zip](https://github.com/livekit/livekit/files/10308432/aboutWebrtc.zip)

I see Nominated false and Selected for all the candidates. It has 4 sessions due to reconnect (At the start it was 2 sessions)

---
How does it look like:
[Screencast from 2022-12-27 17-52-41.webm](https://user-images.githubusercontent.com/3160384/209677122-92465995-7e1a-43fb-b1c1-479fe95051ba.webm)

Related `about:webrtc` 
[aboutWebrtc2.zip](https://github.com/livekit/livekit/files/10308520/aboutWebrtc2.zip)

---

cc @cnderrauber

**Comment by cnderrauber** [comment]
So you disabled the #1226 patch and firefox works well now?

**Comment by nkonev** [comment]
@cnderrauber yes

**Comment by cnderrauber** [comment]
I have test combination of enable/disable udpmux and #1226 in my test server, found udpmux is conflict with #1226, because we closed the duplicate candidate in [496](https://github.com/pion/ice/pull/496) to fix the goroutine leak. But #1226 is required for firefox connect to server though TURN, both w/o udpmux. So the issue is we need a solution to fix the udpmux broken by [496](https://github.com/pion/ice/pull/496) and #1226

**Comment by cnderrauber** [comment]
@nkonev We need to remove the duplicate candidates from NATMapping, Can you try #1270, and add the ip filter config to you config file, it would solve the issue
```
rtc:
    tcp_port: 7881
    udp_port: 7882
    ips:
      includes:
        - 10.0.8.4/24 # your private address that mapping to the public address
```

**Comment by nkonev** [comment]
@cnderrauber 
Your https://github.com/livekit/livekit/pull/1270 is working, along with manual adding ip mask, thank you

```yaml
port: 7880
rtc:
    #node_ip: 92.53.64.83
    udp_port: 7882
    tcp_port: 7881
    #tcp_port: 0
    use_external_ip: true
#    use_ice_lite: true
    use_ice_lite: false
    #port_range_start: 35200
    #port_range_end: 35400
    #force_tcp: true
    #allow_tcp_fallback: false
    ips:
        includes:
#            - 10.0.4.0/24 # your private address that mapping to the public address
            - 172.18.0.0/16
```
also works with UDP-only
```yaml
port: 7880
rtc:
    #node_ip: 92.53.64.83
    udp_port: 7882
    #tcp_port: 7881
    tcp_port: 0
    use_external_ip: true
#    use_ice_lite: true
    use_ice_lite: false
    #port_range_start: 35200
    #port_range_end: 35400
    #force_tcp: true
    allow_tcp_fallback: false
    ips:
        includes:
#            - 10.0.4.0/24 # your private address that mapping to the public address
            - 172.18.0.0/16
```

also works with TCP-only
```yaml
port: 7880
rtc:
    #node_ip: 92.53.64.83
    #udp_port: 7882
    tcp_port: 7881
    #tcp_port: 0
    use_external_ip: true
#    use_ice_lite: true
    use_ice_lite: false
    #port_range_start: 35200
    #port_range_end: 35400
    #force_tcp: true
    #allow_tcp_fallback: false
    ips:
        includes:
#            - 10.0.4.0/24 # your private address that mapping to the public address
            - 172.18.0.0/16
```

Some thoughts:

It was hard to guess which one is the correct
```
[root@selectel videochat]# docker exec -it VIDEOCHATSTACK_livekit.1.ti1haad2y6ulrvlaqhhz01dj5 sh
/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
23402: eth0@if23403: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP 
    link/ether 02:42:0a:00:04:4b brd ff:ff:ff:ff:ff:ff
    inet 10.0.4.75/24 brd 10.0.4.255 scope global eth0
       valid_lft forever preferred_lft forever
23404: eth1@if23405: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:ac:12:00:1b brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.27/16 brd 172.18.255.255 scope global eth1
       valid_lft forever preferred_lft forever
```

So can we somehow reuse the code from rtc/config.go getNAT1to1IPsForConf()
```
	localIPs, err := config.GetLocalIPAddresses(conf.RTC.EnableLoopbackCandidate)
	if err != nil {
		return nil, err
	}
```
to automate choosing the appropriate IP ? It would be helpful, it DevOps/Admin isn't forced to search the IP mask manually.
