### ISSUE TITLE
redis cluster support in livekit-ingress server

### ISSUE THREAD

**Issue by motolies** [livekit/livekit#1292]
**Describe the bug**
My configuration is as follows.

- EC2 installed livekit 1.3.3 version
- EC2 Docker livekit/ingress:latest
- AWS Redis Cluster

```
2023-01-10T04:45:56.869Z	ERROR	livekit	service/ingress.go:106	could not write ingress info	{"error": "CROSSSLOT Keys in request don't hash to the same slot"}
github.com/livekit/livekit-server/pkg/service.(*IngressService).CreateIngressWithUrlPrefix
	/home/runner/go/pkg/mod/github.com/livekit/livekit-server@v1.3.3/pkg/service/ingress.go:106
github.com/livekit/livekit-server/pkg/service.(*IngressService).CreateIngress
	/home/runner/go/pkg/mod/github.com/livekit/livekit-server@v1.3.3/pkg/service/ingress.go:73
github.com/livekit/protocol/livekit.(*ingressServer).serveCreateIngressProtobuf.func2
	/home/runner/go/pkg/mod/github.com/livekit/protocol@v1.3.2-0.20221228091932-fa87d56355d2/livekit/livekit_ingress.twirp.go:771
github.com/livekit/protocol/livekit.(*ingressServer).serveCreateIngressProtobuf
	/home/runner/go/pkg/mod/github.com/livekit/protocol@v1.3.2-0.20221228091932-fa87d56355d2/livekit/livekit_ingress.twirp.go:772
github.com/livekit/protocol/livekit.(*ingressServer).serveCreateIngress
	/home/runner/go/pkg/mod/github.com/livekit/protocol@v1.3.2-0.20221228091932-fa87d56355d2/livekit/livekit_ingress.twirp.go:633
github.com/livekit/protocol/livekit.(*ingressServer).ServeHTTP
	/home/runner/go/pkg/mod/github.com/livekit/protocol@v1.3.2-0.20221228091932-fa87d56355d2/livekit/livekit_ingress.twirp.go:605
net/http.(*ServeMux).ServeHTTP
	/opt/hostedtoolcache/go/1.19.4/x64/src/net/http/server.go:2487
github.com/urfave/negroni/v3.Wrap.func1
	/home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.0.0/negroni.go:59
github.com/urfave/negroni/v3.HandlerFunc.ServeHTTP
	/home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.0.0/negroni.go:33
github.com/urfave/negroni/v3.middleware.ServeHTTP
	/home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.0.0/negroni.go:51
net/http.HandlerFunc.ServeHTTP
	/opt/hostedtoolcache/go/1.19.4/x64/src/net/http/server.go:2109
github.com/livekit/livekit-server/pkg/service.(*APIKeyAuthMiddleware).ServeHTTP
	/home/runner/go/pkg/mod/github.com/livekit/livekit-server@v1.3.3/pkg/service/auth.go:84
github.com/urfave/negroni/v3.middleware.ServeHTTP
	/home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.0.0/negroni.go:51
github.com/rs/cors.(*Cors).ServeHTTP
	/home/runner/go/pkg/mod/github.com/rs/cors@v1.8.3/cors.go:271
github.com/urfave/negroni/v3.middleware.ServeHTTP
	/home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.0.0/negroni.go:51
github.com/urfave/negroni/v3.(*Recovery).ServeHTTP
	/home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.0.0/recovery.go:210
github.com/urfave/negroni/v3.middleware.ServeHTTP
	/home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.0.0/negroni.go:51
github.com/urfave/negroni/v3.(*Negroni).ServeHTTP
	/home/runner/go/pkg/mod/github.com/urfave/negroni/v3@v3.0.0/negroni.go:111
net/http.serverHandler.ServeHTTP
	/opt/hostedtoolcache/go/1.19.4/x64/src/net/http/server.go:2947
net/http.(*conn).serve
	/opt/hostedtoolcache/go/1.19.4/x64/src/net/http/server.go:1991
```

**Server**
- Version: 1.3.3
- Environment: AWS EC2
- any other information about your deployment setup

**livekit server conf**
```
port: 7880
rtc:
  udp_port: 7882
  tcp_port: 7881
  port_range_start: 40000
  port_range_end: 60000
  use_external_ip: true
  turn_servers:
    - host: mydomain.com
      port: 3478
      protocol: udp
      username: "username"
      credential: "credential"
redis:
  cluster_addresses:
    - redis-dev-0001-001.amazonaws.com:6379
    - redis-dev-0001-002.amazonaws.com:6379
keys:
  KEY: VALUE
logging:
  json: false
  level: info

ingress:
  rtmp_base_url: rtmp://ingress.mydomain.com/app
```

**livekit ingress conf**

```
api_key: KEY
api_secret: VALUE
ws_url: wss://livekit.mydomain.com:7880
redis:
  address: redis-dev.amazonaws.com:6379
cpu_cost:
  rtmp_cpu_cost: 2.0
```

**Client**
- SDK: livekit-cli
- Version: livekit-cli version 1.2.2

**To Reproduce**

livekit-cli create-ingress --request ingress.json

```
{
  "name": "stark-tower-ingress",
  "room_name": "stark-tower",
  "participant_identity": "stark-tower-ingress",
  "participant_name": "stark-tower-ingress-name"
}
```

**Expected behavior**
Generate ingress address
