### ISSUE TITLE
RoomService.CreateRoom API call returns Twirp "Could not find any available nodes" error when creating multiple rooms

### ISSUE THREAD

**Issue by Lyx52** [livekit/livekit#1851]
**Describe the bug**
Twirp error when creating multiple rooms
2023-07-05T11:03:13.459Z        INFO    livekit webhook/url_notifier.go:74      sent webhook    {"url": "--------", "event": "participant_joined"}
2023-07-05T11:03:15.423Z        INFO    livekit server/main.go:265      exit requested, shutting down   {"signal": "terminated"}
2023-07-05T11:03:19.891Z        INFO    livekit service/twirp.go:128    API RoomService.CreateRoom      {
  "service": "RoomService",
  "method": "CreateRoom",
  "room": "5fde8bda-0374-4b1e-87e7-b658c65b06c9",
  "request": "name:\"5fde8bda-0374-4b1e-87e7-b658c65b06c9\" empty_timeout:900 max_participants:25 metadata:\"{\\\"room_title\\\":\\\"test\\\", \\\"is_recording\\\":false, \\\"is_active_rtmp\\\":false, \\\"parent_room_id\\\":\\\"\\\", \\\"is_breakout_room\\\":false, \\\"started_at\\\":\\\"1688554999\\\", \\\"room_features\\\":{\\\"allow_webcams\\\":true, \\\"mute_on_start\\\":false, \\\"allow_screen_share\\\":true, \\\"allow_rtmp\\\":true, \\\"allow_view_other_webcams\\\":true, \\\"allow_view_other_users_list\\\":true, \\\"admin_only_webcams\\\":false, \\\"allow_polls\\\":true, \\\"room_duration\\\":\\\"0\\\", \\\"recording_features\\\":{\\\"is_allow\\\":true, \\\"is_allow_cloud\\\":true, \\\"enable_auto_cloud_recording\\\":false, \\\"is_allow_local\\\":true}, \\\"chat_features\\\":{\\\"allow_chat\\\":true, \\\"allow_file_upload\\\":true, \\\"allowed_file_types\\\":[\\\"jpg\\\", \\\"png\\\", \\\"jpeg\\\", \\\"svg\\\", \\\"pdf\\\", \\\"docx\\\", \\\"txt\\\", \\\"xlsx\\\", \\\"pptx\\\", \\\"zip\\\", \\\"mp4\\\", \\\"webm\\\", \\\"mp3\\\"], \\\"max_file_size\\\":\\\"50\\\"}, \\\"shared_note_pad_features\\\":{\\\"allowed_shared_note_pad\\\":false, \\\"is_active\\\":false, \\\"visible\\\":false, \\\"node_id\\\":\\\"\\\", \\\"host\\\":\\\"\\\", \\\"note_pad_id\\\":\\\"\\\", \\\"read_only_pad_id\\\":\\\"\\\"}, \\\"whiteboard_features\\\":{\\\"allowed_whiteboard\\\":true, \\\"visible\\\":false, \\\"preload_file\\\":\\\"\\\", \\\"whiteboard_file_id\\\":\\\"\\\", \\\"file_name\\\":\\\"\\\", \\\"file_path\\\":\\\"\\\", \\\"total_pages\\\":0}, \\\"external_media_player_features\\\":{\\\"allowed_external_media_player\\\":true, \\\"is_active\\\":false}, \\\"waiting_room_features\\\":{\\\"is_active\\\":false, \\\"waiting_room_msg\\\":\\\"\\\"}, \\\"breakout_room_features\\\":{\\\"is_allow\\\":true, \\\"is_active\\\":false, \\\"allowed_number_rooms\\\":6}, \\\"display_external_link_features\\\":{\\\"is_allow\\\":true, \\\"is_active\\\":false}, \\\"ingress_features\\\":{\\\"is_allow\\\":true, \\\"input_type\\\":\\\"RTMP_INPUT\\\", \\\"url\\\":\\\"\\\", \\\"stream_key\\\":\\\"\\\"}, \\\"speech_to_text_translation_features\\\":{\\\"is_allow\\\":false, \\\"is_allow_translation\\\":true, \\\"is_enabled\\\":false, \\\"is_enabled_translation\\\":false, \\\"allowed_speech_langs\\\":[], \\\"allowed_speech_users\\\":[], \\\"allowed_trans_langs\\\":[]}, \\\"end_to_end_encryption_features\\\":{\\\"is_enabled\\\":false}}, \\\"default_lock_settings\\\":{\\\"lock_microphone\\\":false, \\\"lock_webcam\\\":false, \\\"lock_screen_sharing\\\":true, \\\"lock_chat\\\":false, \\\"lock_chat_send_message\\\":false, \\\"lock_chat_file_share\\\":false, \\\"lock_private_chat\\\":false, \\\"lock_whiteboard\\\":true, \\\"lock_shared_notepad\\\":true}, \\\"copyright_conf\\\":{\\\"display\\\":true, \\\"text\\\":\\\"Powered by <a href=\\\\\\\"https://www.plugnmeet.org\\\\\\\" target=\\\\\\\"_blank\\\\\\\">plugNmeet</a>\\\"}}\"",
  "duration": "4.492194ms",
  "status": "500",
  "error": "could not create room: could not find any available nodes",
  "code": "internal"
}

**Server**
- Version: v1.4.3
- Environment: Docker image
- Minimal setup with single docker service

**Client**
- SDK: livekit/server-sdk-go
- Version: v1.0.12 (Latest PlugNMeet server)

**To Reproduce**
1. Create a room
2. Client joins the room
3. Try to create the second room
4. See error in livekit logs

**Expected behavior**
Livekit should create both rooms, and should not fail.

**Additional context**
Im using PlugNMeet project(v1.4.4), but for livekit im using is a seperate docker service which uses "host" network mode. Additionally Im using Ingress and Egress services.

This is my livekit config:
```
port: 7880
rtc:
  port_range_start: 50000
  port_range_end: 60000
  tcp_port: 7881
  allow_tcp_fallback: true
  use_external_ip: true
  stun_servers:
    - stun.l.google.com:19302
redis:
  address: 127.0.0.1:6379
  password: "xxxxxx"
  username: "xxxxxx"
  db: 0
room:
  auto_create: false
  enable_remote_unmute: true
keys:
  XXXXX: xxxxxxxx
webhook:
  api_key: xxxxxx
  urls:
    - "https://plugnmeet.xxxx.xxx/webhook"
    - "https://media-api.xxxx.xxx/livekit/webhook"
limit:
  num_tracks: -1
  bytes_per_sec: 1_000_000_000
ingress:
  rtmp_base_url: "rtmp://xxx.xxx.xxx.xxx:1935/live"
turn:
  enabled: true
  udp_port: 443
  tls_port: 5439
  relay_range_start: 1024
  relay_range_end: 30000
  external_tls: true
  domain: plugnmeet.xxxx.xxx

```
