### ISSUE TITLE
PodSecurityContext fsGroup flag prevents livekit-server to start

### ISSUE THREAD

**Issue by kannonski** [livekit/livekit#1889]
**Describe the bug**
By setting the securityContext, podSecurityContext in the `values.yaml` we end up with an issue:

```
livekit:
  rtc:
    use_external_ip: true
  redis:
    sentinel_master_name: mymaster
    sentinel_addresses:
      - sentinel-0.sentinel:5000
      - sentinel-1.sentinel:5000
      - sentinel-2.sentinel:5000
  turn:
    enabled: false
  key_file: keys.yaml
  logging:
    json: true

storeKeysInSecret:
  enabled: true
  existingSecret: livekit-api-keys


securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

podSecurityContext:
  fsGroup: 1000
```

By Default the helm chart will try to set `0600` rights on the `keys.yaml`. When we set the fsGroup, kubernetes will change the rights of the file `keys.yaml` and set them to `0640`. The livekit-server application checks if the rights of the file are set to `0600`, thus the application cannot start...
There is an issue raised and discussed on [kubernetes repo](https://github.com/kubernetes/kubernetes/issues/57923#issuecomment-1380630750) about this.

**Server**
- Version: 1.4.3
- Environment: GCP ...

**Expected behavior**
When fsGroup flag is set, livekit should allow `0640` permissions on the keys.yaml file
