### ISSUE TITLE
Multiple rooms creation with same name on updating the permissions

### ISSUE THREAD

**Issue by heyarviind** [livekit/livekit#1943]
**Describe the bug**
2 rooms get created when we try to change the participants' permission. It happens at very random intervals.

**Server**
- Version: 1.4.4
- Environment: Production, Ubuntu 22.04.2 LTS
- Architecture: 3 AWS EC2 Instances (Behind a load balancer), each running their own Livekit node (with their own config file), connected to a common redis server, and TURN server.

**Client**
- SDK: js
- Version: 1.12.1
- Framework: Next.js

**To Reproduce**
1. Generate a token for each participant, without the audio permission
2. Let the participants join a room
3. Hit the API `<domain-name>/twirp/livekit.RoomService/UpdateParticipant` to update the participant's permission and use the sample payload below:

```
{
         room: <room-name>,
         identity: <participant-identity>,
         permission: {
           can_publish: true,
             can_subscribe: true,
             can_publish_data: true,
             can_publish_sources: [1,2],
           },
         },
```

**Expected behavior**
Participant's permission should be updated without any new room creation

**Screenshots**
If applicable, could you add screenshots to help explain your problem?

**Additional context**
We started to face this issue when we used 2 Livekit nodes that were behind the load balancer. Earlier on one node, we didn't face any issues.

Moreover, we noticed, on random occasions, **when we update the permission**, the data in redis gets deleted, and Livekit creates a new room with the same name, and the new participants join the new room. The old room stays online until everyone leaves.

**Comment by davidzhao** [comment]
@heyarviind Could you share the config.yaml used? (with keys redacted)

**Comment by heyarviind** [comment]
Sure, here is the config file we are using for all the nodes

![Group 14](https://github.com/livekit/livekit/assets/21043614/98f7c1a9-e3e6-495f-9a22-b2d396d3418b)

**Comment by davidzhao** [comment]
Please upload the full text file instead of a partial screenshot. I'm unable to replicate any of this from an image.

**Comment by heyarviind** [comment]
oh sorry, here is the entire file:

```
port: 7880

redis:
  cluster_addresses:
    - <my-redis-domian>.amazonaws.com:6379

rtc:
  port_range_start: 50000
  port_range_end: 60000
  tcp_port: 7881
  use_external_ip: true

  turn_servers:
    - host: <my-turn-server-domain>
      port: 5349
      protocol: tls
      username: "tfu"
      credential: <password>

    - host: <my-turn-server-domain>
      port: 3478
      protocol: tcp
      username: "tfu"
      credential: <password>

    - host: <my-turn-server-domain>
      port: 3478
      protocol: udp
      username: "tfu"
      credential: <password>

  congestion_control:
    enabled: true
    allow_pause: false
```
