### ISSUE TITLE
1.2.4 seems to have broken redis.cluster_addresses

### ISSUE THREAD

**Issue by Katsuyu** [livekit/livekit#2129]
When upgrading our Livekit Cluster (Docker Images) composed of 3 instances, each with a Redis which is part of a redis-cluster (so 3 Livekit instances and 3 redis) from 0.15.6 to 1.4.4, I saw that the Livekit instances had trouble connecting to their Redis instance with those logs 

```
livekitserver_production-livekit-1  | 2023-10-05T08:54:02.319Z	INFO	livekit	redis/redis.go:82	connecting to redis	{"cluster": true, "addr": ["my_redis_addr1:6379", "my_redis_addr2:6379", "my_redis_addr3:6379"]}
livekitserver_production-livekit-1  | 2023-10-05T08:54:04.803Z	INFO	livekit	rtc/config.go:333	failed to get external ip	{"local": "172.17.0.1", "err": "could not validate external IP"}
livekitserver_production-livekit-1  | 2023-10-05T08:54:04.803Z	INFO	livekit	rtc/config.go:333	failed to get external ip	{"local": "172.18.0.1", "err": "could not validate external IP"}
livekitserver_production-livekit-1  | 2023-10-05T08:54:04.804Z	INFO	livekit	rtc/config.go:333	failed to get external ip	{"local": "172.19.0.1", "err": "could not validate external IP"}
livekitserver_production-livekit-1  | 2023-10-05T08:54:04.804Z	INFO	livekit	rtc/config.go:111	using external IPs	{"ips": ["IP_of_redis1/IP_of_redis1", "172.17.0.1/172.17.0.1", "172.18.0.1/172.18.0.1", "172.19.0.1/172.19.0.1"]}
livekitserver_production-livekit-1  | 2023-10-05T08:54:04.808Z	INFO	livekit	service/turn.go:127	Starting TURN server	{"turn.relay_range_start": 30000, "turn.relay_range_end": 40000, "turn.portTLS": 5349, "turn.externalTLS": true, "turn.portUDP": 443}
livekitserver_production-livekit-1  | could not get rooms: CLUSTERDOWN Hash slot not served
```

On 1.2.4 or 1.2.5 I also have this logs that are not here anymore in 1.4.4
```
livekitserver_production-livekit-1  | could not parse config: yaml: unmarshal errors:
livekitserver_production-livekit-1  |   line 9: field cluster_addresses not found in type config.RedisConfig
```

And then, because Livekit doesn't start, Caddy is crashing and I'm unable to access Livekit.

When debugging this, I saw that I can upgrade my Livekit up to v1.2.3 and everything works fine but then in v.1.2.4 and above, the error keeps reappearing.

I searched in the changelog for the change in 1.2.4 that could have broken my config but the 1.2.4 doesn't exist in the CHANGELOG even though there is a tag in the project and a Docker image.

Here's my livekit.yaml config : 
```
port: 7880
rtc:
    tcp_port: 7881
    port_range_start: 50000
    port_range_end: 60000
    use_external_ip: true
redis:
    password: "MY_SECURE_PASSWORD"
    cluster_addresses:
      - my_redis_addr1:6379
      - my_redis_addr2:6379
      - my_redis_addr3:6379
turn:
    enabled: true
    domain: my_livekit_turn_addr
    cert_file: ""
    key_file: ""
    tls_port: 5349
    udp_port: 443
    external_tls: true
keys:
    (I suppose this should stay hidden)
```
The config is the same for the 3 Livekit instance (except for the turn server adress)

I also saw that in recent example of the livekit config, there is no more `cluster_adresses` in the redis config but only sentinel config
Did Livekit drop the support for redis cluster in 1.2.4 ? Do you know if there is a way to fix this while still using Redis cluster ? 

**Server**
- Version: 1.2.3
- Environment: Docker Images
- 3 Livekit Instances in a cluster with a cluster of 3 redis 

**To Reproduce**
1- Create Livekit cluster in 1.2.3 with redis cluster
2- Upgrade in 1.2.4
3- It should not work anymore
