### ISSUE TITLE
Cant Unmute Track By Remote

### ISSUE THREAD

**Issue by akhmadali22** [livekit/livekit#2318]
hello I would like to unmute some track on participant in room
this is the data I sent:
`{"room": "room1", "roomID": "RM_VNCj75Z6DomF", "participant": "user1", "pID": "PA_JAWHMduA7gsk", "remote": false, "trackID": "TR_AM6yaEh6BvzDyQ", "muted": false}`

and this error response:
`cannot unmute track, remote unmute is disabled`

why do I get this error, even though I have configured it in `config.yaml` by setting `enable_remote_unmute: true`, 
this my config.yaml:
```
port: 7880
log_level: info
rtc:
  tcp_port: 7881
  port_range_start: 30000
  port_range_end: 40000
  use_external_ip: false
keys:
  devkey: secret
room:
  enabled_codecs:
    - mime: audio/opus
    - mime: audio/red
  enable_remote_unmute: true
turn:
  enabled: false
```

is there something I missed?
