### ISSUE TITLE
Noticeable lag when trying to share a local video window

### ISSUE THREAD

**Issue by Kabochar** [livekit/livekit#2430]
## Describe the bug
When client A shares the local screen of the programme that plays the video, client B can obviously feel the video stuttering (the screen is not smooth). 

livekit-server, client A and client B are all on the same LAN segment 10.0.0.0/24, not through the public network.

So, I would like to ask you guys, how can I do the troubleshooting of the above problem in this situation?

Local livekit-server resource situation when lagging occurs
1, Process usage: CPU load 3.3, Memory 0.6
2, Network: rx: 26 kbit/s 52 p/s tx: 8 kbit/s 10 p/s

## To Reproduce
On the same LAN, Client A is using livekit for local video screen sharing and Client B is using edge/chrome Web Browser to view the video content shared by client A.

## Server	
Machine
4C 8G 1000Mb

Server
livekit-server version 1.5.1

Web Front
livekit-client version 1.15.4

Deployment
raw binary in linux

livekit.yaml
```
keys:
  key1: value1xxxxxx
port: 7880
redis:
  address: 127.0.0.1:6379
  db: 0
  username:
  password:
rtc:
  #batch_io:
  #  batch_size: 128
  #  max_flush_interval: 5ms
  port_range_end: 51000
  port_range_start: 50000
  tcp_port: 7881
  udp_port: 7882-7892
  use_external_ip: false
turn:
  cert_file: ../config/demo.pem.crt
  domain: 10.0.0.64
  enabled: true
  external_tls: true
  key_file: ../config/demo.key
  tls_port: 13478
  udp_port: 13478
webhook:
  api_key: key1
  urls:
  - http://127.0.0.1:7051/webhook
room:
  enabled_codecs:
  - mime: audio/opus
  - mime: audio/red
  - mime: video/h264
```
## Expected behavior
The screen can be played back relatively smoothly
