### ISSUE TITLE
api_key is required to use webhooks

### ISSUE THREAD

**Issue by v57** [livekit/livekit#2482]
**Describe the bug**
LiveKit server not starts when I enable webhooks with api_key and urls. It throws an error `api_key is required to use webhooks`. I tried different values and always getting same error. I have docker-compose and config yaml so it would be easy to reproduce

**Server**
- Version: 1.5.2
- Environment: Docker
- any other information about your deployment setup

**To Reproduce**
Here is my `livekit.yaml`
```
port: 7880
bind_addresses:
    - ""
rtc:
    tcp_port: 7881
    port_range_start: 50000
    port_range_end: 60000
    use_external_ip: false
    enable_loopback_candidate: false
redis:
    address: redis:6379
keys:
    KEY: SECRETSECRETSECRETSECRETSECRETSECRET
webhook:
  api_key: 'mywebhook'
  urls:
    - 'website.com/webhook'
```
And `docker-compose.yaml`
```
version: '3.8'
services:
  livekit:
    image: livekit/livekit-server:v1.5.2
    command: --config /etc/livekit.yaml
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
  redis:
    image: redis:alpine
```
