### ISSUE TITLE
[Bug] Cannot connect external TURN Server via Livekit

### ISSUE THREAD

**Issue by thaidmfinnick** [livekit/livekit#2823]
**Describe the bug**
Hi @cloudwebrtc, I have built my own TURN server before so I use it instead of embedded Livekit provide. I tested my TURN Server with [Trickle Ice Test](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) and it works. But I run with Livekit Connection Tester, it shows `Cannot connect via TURN`.

**Server**
- Version: [1.7.0]
- Environment: Docker, VM
- Deploy follow [docs](https://docs.livekit.io/home/self-hosting/vm/)

**To Reproduce**
1. Setup server follows docs
2. Test with Livekit Connection Tester
3. Setup `rtc.turn_servers`

**My Livekit.yaml configuration**
```yaml
port: 7880
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: true
  turn_servers:
   - host: redacted
     port: 443
     protocol: tls
     username: redacted
     credential: redacted
redis:
  address: localhost:6379
  username: ""
  password: ""
  db: 0
logging:
  level: debug
keys:
  redacted
webhook:
  api_key: redacted
  urls:
    - redacted
```

**Expected behavior**
Can connect to external TURN Server through Livekit.

**Screenshots**
 Tested with Livekit Connection Test on Chrome, Safari. And with Flutter Client.
<img width="890" alt="Screenshot 2024-06-27 at 11 05 08" src="https://github.com/livekit/livekit/assets/83997264/c5671d9d-eba3-4e60-9632-1e618e55d0f9">
