### ISSUE TITLE
when livekit config redis cluster address, its not works

### ISSUE THREAD

**Issue by grootgordon** [livekit/livekit#2836]
**Describe the bug**
When livekit-server using the Redis cluster configuration, it does not work correctly.

**Server**
- Version: [1.6.0]
- Environment: [local dev, centos:7.2.1511]

**REDIS**
- Redis Version: [5.x.x] cluster mode

**To Reproduce**
1. config.yaml as follow 
```yaml
bind_addresses: 
  - 0.0.0.0
#  - 127.0.0.1
port: 7880


redis:
  password: mypasswd
  cluster_addresses:
    - redis-cluster.privite-server.local:6379
#rtc:
#  port_range_start: 50000
#  port_range_end: 60000
#  tcp_port: 7881
#  use_external_ip: true
keys:
  devkey: secret
```
3. `./bin/livekit-server --config ./config/config.yaml`
4. See error as follow
```
INFO livekit redis/redis.go:130 connecting to redis {"cluster": true, "addr": [redis-cluster.privite-server.local:6379"]}
could not get rooms: MOVED 4321 192.168.1.130:6379
```

**Expected behavior**
When using Redis cluster, I hope it works.

Using redis in single mode works well for me.

Any advice for resolving this problem will be greatly appreciated. Thank you :)

**Comment by grootgordon** [comment]
oops!
we only config one addr , it will go to `opts.Simple`
https://github.com/redis/go-redis/blob/master/universal.go#L240
```go
func NewUniversalClient(opts *UniversalOptions) UniversalClient {
	if opts.MasterName != "" {
		return NewFailoverClient(opts.Failover())
	} else if len(opts.Addrs) > 1 {
		return NewClusterClient(opts.Cluster())
	}
	return NewClient(opts.Simple())
}
```

By test, when configuring two Redis cluster addresses, it worked, although those two Redis addresses are the same. The correct config.yaml is as follows. I hope this will be helpful for someone who is stuck here :)
```
bind_addresses: 
  - 0.0.0.0
#  - 127.0.0.1
port: 7880


redis:
  password: mypasswd
  cluster_addresses:
    - redis-cluster.privite-server.local:6379
    - redis-cluster.privite-server.local:6379
#rtc:
#  port_range_start: 50000
#  port_range_end: 60000
#  tcp_port: 7881
#  use_external_ip: true
keys:
  devkey: secret
```
