### ISSUE TITLE
Livekit ignore rtc ips exclude configs in livekit.yaml

### ISSUE THREAD

**Issue by dbastos** [livekit/livekit#3012]
**Describe the bug**
Livekit ignore rtc ips exclude configs in livekit.yaml

**Server**
- Version: 1.7.2
- Environment: Production (Bare metal server in hetzner)
- Using Deploy to VM guide

**Client**
- SDK: JS
- Version: 2.5.1

**To Reproduce**
1. change the configs in livekit.yaml
```yaml
rtc:
    tcp_port: 7881
    port_range_start: 50000
    port_range_end: 60000
    use_external_ip: true
    enable_loopback_candidate: false
    ips:
      excludes:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
``` 
2. Start LiveKit

Log info:
```text
livekit-1  | 2024-09-17T03:34:52.775Z	INFO	livekit	rtcconfig/webrtc_config.go:88	using external IPs	{"ips": ["xxx.xxx.xxx.xxx/xxx.xxx.xxx.xxx", "172.17.0.1/172.17.0.1"]}  
 ``` 
**Expected behavior**
Ignore the internal ip 172.17.0.1

**Additional context**
I want to ignore this Ip because Firefox is generating a lot o Ice Candidates to this ip and, as expected, failed! This is causing a lot of ports usage in the server side. 
Thks!
Doug
