### ISSUE TITLE
Intranet and extranet solutions (Client custom cotrun server address）

### ISSUE THREAD

**Issue by wudanwei** [livekit/livekit#3028]
hello，I have a problem.
  In a firewall network environment, such as the Intranet,Intranet users cannot communicate with extranet users due to firewall and network faults.
  for example：The livekit configuration is as follows.

```
rtc:
  udp_port: 7882
  tcp_port: 7881
  use_external_ip: false
  node_ip: 61.165.184.227
  enable_loopback_candidate: false
  use_ice_lite: false
  stun_servers:
     - 61.165.184.228:3478
  turn_servers:
     - host: 61.165.184.228
      port: 3478
      protocol: udp
      username: "user01"
      credential: "password1"
```
Both the livekit service and the cotrun service are in the Intranet environment,The Intranet client can use 61.165.184.227:7882 to properly communicate with video users,Then the 61.165.184.227:7880 service of the Intranet is mapped to the extranet 192.168.43.10:7880. If the Intranet wants to communicate with the extranet terminal, the SDK of the Intranet client uses 61.165.184.227:7880. The external network client SDK uses 192.168.43.10:7880 service, which is not possible, because the cotrun service address is configured in livekit, and the external network cannot access it. Can you refer to Tencent Cloud's enterprise internal and external network solution to conduct proxy?
```
const trtc = TRTC.create(); 
await trtc.enterRoom({
  ...,
  proxy: {
    // 设置 Websocket 代理，用于中转 SDK 与 TRTC 后台的信令数据包。
    websocketProxy: 'wss://proxy.example.com/ws/',
    // 设置 turn server，用于中转 SDK 与 TRTC 后台的媒体数据包。14.3.3.3:3478 为 turn server 的 ip 及端口。
    turnServer: { url: '14.3.3.3:3478', username: 'turn', credential: 'turn', credentialType: 'password' },
    // 默认 SDK 会直连 TRTC 服务器，如果连不上，则会尝试连 TURN server。你可以指定 'relay' 来强制连接 TURN server。
    iceTransportPolicy: 'all', 
    // SDK 默认会向 yun.tim.qq.com 域名上报日志，但若该域名在您的内网无法访问，您需要给该域名开白名单或者配置以下日志代理。
    // 设置日志上报代理，日志是排查问题的关键数据，请务必设置该代理。
    loggerProxy: 'https://proxy.example.com/logger/',
  }
})
```
