### ISSUE TITLE
Unable to send/recieve any `audioFeatures` in self hosted livekit-server

### ISSUE THREAD

**Issue by cyai** [livekit/livekit#3038]
I have a linode server and I am self hosting the livekit-server on it. Here is my `livekit.yaml` config file

```yaml
port: 7880
log_level: info

rtc:
    tcp_port: 7881
    port_range_start: 50000
    port_range_end: 60000
    use_external_ip: true

redis:
    address: 127.0.0.1:6379

keys:
    API_KEY: SECRET_KEY

room:
  enabled_codecs:
    - mime: audio/opus
    # - mime: audio/red
    - mime: video/vp8
    - mime: video/vp9
    - mime: video/h264
    - mime: video/av1
```

And I have a script that i run to manage the worker. But if I run the script lcoally to connect to the websocket url on the linode server then everything works correclty and I get the responses back. But when I try to run the script on the linode server itself by connecting to the websocket url on the linode hosted livekit-server then I am unable to recieve any audio (Subscribe to Track). 
    
### My logs in the livekit-server:
    
- Script run locally:
```
{
  "room": "room-063304",
  "roomID": "RM_od92dfmCHFL9",
  "participant": "agent-AJ_KDY9XjgJpX2j",
  "pID": "PA_aXVaPMsXWAKV",
  "remote": false,
  "kind": "audio",
  "trackID": "TR_AMTUwVgWPn5EzH",
  "webrtcTrackID": "71ed890d-d36e-4207-8888-11123a1352d1",
  "rid": "",
  "SSRC": 1144276994,
  "mime": "audio/opus",
  "trackInfo": {
    "sid": "TR_AMTUwVgWPn5EzH",
    "name": "assistant_voice",
    "disableDtx": true,
    "source": 2,
    "mimeType": "audio/opus",
    "mid": "0",
    "disableRed": true,
    "stream": "camera",
    "version": {
      "unixMicro": 1727097884503728
    },
    "audioFeatures": [
      1
    ]
  }
}
```

- Script run on linode server:
```{
  "room": "room-448422",
  "roomID": "RM_Mak39rmD86kk",
  "participant": "participant-448422",
  "pID": "PA_URSkvS56Wzze",
  "remote": false,
  "kind": "audio",
  "trackID": "TR_AM6X6Sg9DWwgZu",
  "webrtcTrackID": "e7793dff-a92a-4019-8586-ab407d5528ec",
  "rid": "",
  "SSRC": 628668937,
  "mime": "audio/opus",
  "trackInfo": {
    "sid": "TR_AM6X6Sg9DWwgZu",
    "source": 2,
    "mimeType": "audio/opus",
    "mid": "0",
    "stream": "camera",
    "version": {
      "unixMicro": 1727099174157457
    }
  }
}
```

As you can see there is no `audioFeatures` being sent.
