### ISSUE TITLE
Error: Request failed with status 401: Unauthorized

### ISSUE THREAD

**Issue by Z3oM** [livekit/livekit#3109]
Hello everyone!

I want to use LiveKit in my application, but I've encountered an issue. I deployed a container with LiveKit on my server and defined it as follows:

```yaml
  livekit-server:
    image: livekit/livekit-server
    volumes:
      - /opt/livekit/logs:/var/log/livekit
      - /opt/livekit/conf/livekit.yaml:/livekit.yaml
    container_name: livekit-server
    command: --config /livekit.yaml
    environment:
      LIVEKIT_API_HOST: 0.0.0.0
      LIVEKIT_REDIS_ADDRESS: redis:6379
    ports:
      - "7880:7880"   # port for REST API
      - "7881:7881"   # port for WebSocket API
      - "7882:7882/udp"
    networks:
      - front-network
      - back-network

  redis:
    image: redis:6
    container_name: livekit-redis
    networks:
      - back-network
```

Afterward, I set up port forwarding to access this container from my computer, and the forwarding works.

When I send the following cURL command in the terminal:

```cUrl
lk.exe create-token --url http://localhost:7880 --api-key API_KEY --api-secret SECRET_KEY --join --room my-first-room --identity user1 --valid-for 24h
```

LiveKit returns a token and room information. However, when I try to retrieve rooms through my ExpressJS backend, as shown below:

```typescript
    const roomService = new RoomServiceClient("http://127.0.0.1:7880", API_KEY, SECRET_KEY);

    roomService.listRooms().then((rooms: Room[]) => {
      console.log('existing rooms', rooms);
    }).catch((error) => {
      console.error('Error:', error);
    });
```

I receive an error: `Error: Request failed with status 401: Unauthorized`

Meanwhile, the LiveKit container log shows this:

```log
WARN    livekit service/auth.go:95      error handling request  {"status": 401, "method": "POST", "path": "/twirp/livekit.RoomService/ListRooms", "error": "invalid token: eyJhbGciOiJIUzI1NiJ9.eyJ2aWRlbyI6eyJyb29tTGlzdCI6dHJ1ZX0sImlzcyI6IkFQSU1NZmNWamtHR2NUUSIsImV4cCI6MTcyOTA5MTQzNCwibmJmIjowfQ.kf39MVbSVqRBP4mSN6YIRUL8v2HMWrx-hOM36qyM1zU, error: go-jose/go-jose/jwt: validation failed, token is expired (exp)"}
```

Where did I go wrong? Also, when I access `http://127.0.0.1:7880/` directly in the browser, it displays "OK." So, LiveKit is running, and the keys seem correct. I just can't understand what the issue is. Thanks in advance.
