### ISSUE TITLE
could not validate external IP and UDP receive buffer is too small for a production set-up

### ISSUE THREAD

**Issue by zoujiaqing** [livekit/livekit#3203]
```log
./livekit-server --config ./livekit.yaml
{"level":"warn","ts":1732616973.5684533,"logger":"livekit","caller":"rtcconfig/ip.go:272","msg":"could not validate external IP","ip":"139.11*.*"error":"context canceled"}
{"level":"warn","ts":1732616973.5701373,"logger":"livekit","caller":"rtcconfig/rtc_unix.go:31","msg":"UDP receive buffer is too small for a production set-up","current":425984,"suggested":5000000}
```

livekit.yaml
```yaml
port: 7880
bind_addresses:
    - "0.0.0.0"
logging:
  level: warn
  json: true
  pion_level: error
rtc:
  tcp_port: 7881
  udp_port: 7882
  use_external_ip: true
  enable_loopback_candidate: false
redis:
  address: 127.0.0.1:6379
  db: 1
turn:
  enabled: false
  tls_port: 5349
  udp_port: 3478
  external_tls: true
keys:
  appkey: secret123456789012345678901234567890
room:
  empty_timeout: 60
  departure_timeout: 1
```

debian linux version
```log
uname -a
Linux debian 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux
```

livekit-server version is 1.8.0
