### ISSUE TITLE
Use public domain turn.domain for UDP iceServers

### ISSUE THREAD

**Issue by viplifes** [livekit/livekit#3233]
**Describe the bug**
Now server return iceServers which use NodeIp for TURN/UDP, but domain for TURN/TCP:
```
{ iceServers: [turn:10.68.59.209:3478?transport=udp, turns:livekit-turn-dev.host.com:443?transport=tcp], iceTransportPolicy: all, bundlePolicy: balanced, rtcpMuxPolicy: require, iceCandidatePoolSize: 0 }
```

The line of code in which this logic is implemented:
https://github.com/livekit/livekit/blob/d8629172494f046a9827edbab68e5a7a62833772/pkg/service/roommanager.go#L928C77-L928C83

**Server**
- Version: [1.8.0]
- Environment: Kubernetes

**To Reproduce**
```
livekit:
  prometheus:
    port: 6789
  log_level: info
  rtc:
    use_external_ip: false
    tcp_port: 7881
    udp_port: 7882
  turn:
      enabled: true
      domain: livekit-turn-dev.host.com
      tls_port: 443
      udp_port: 3478
      external_tls: true
```

**Expected behavior**
Is it possible to use a domain for UDP also?
```
{ iceServers: [turn:livekit-turn-dev.host.com:3478?transport=udp, turns:livekit-turn-dev.host.com:443?transport=tcp], iceTransportPolicy: all, bundlePolicy: balanced, rtcpMuxPolicy: require, iceCandidatePoolSize: 0 }
```
