### ISSUE TITLE
Cannot be combined with frpc for use

### ISSUE THREAD

**Issue by ProgrammerMao** [livekit/livekit#3330]
**Describe the bug**

**Server**
- Version: 1.8.3
- Environment: Docker
- any other information about your deployment setup
  - Using nginx instead of caddy (Nginx is using port 443 for reverse proxy of all other services)
  - Using FRP for forwarding

**Client**
- https://github.com/msgbyte/tailchat/tree/master/server/plugins/com.msgbyte.livekit (I used Project on cloud.livekit.io to meet with my self built tailcaht and it was successful)

**To Reproduce**
1. Annotate the caddy section in docker-compose.env
```
services:
  # caddy:
  #   image: livekit/caddyl4
  #   command: run --config /etc/caddy.yaml --adapter yaml
  #   restart: unless-stopped
  #   network_mode: "host"
  #   volumes:
  #     - ./caddy.yaml:/etc/caddy.yaml
  #     - ./caddy_data:/data
  livekit:
    image: livekit/livekit-server:v1.8.3
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
  redis:
    image: redis:7-alpine
    command: redis-server /etc/redis.conf
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./redis.conf:/etc/redis.conf
```
2.Modifying livekit.yaml does not require configuring the port of the certificate, ensuring consistency with the port of the FRP
```
port: 7880
bind_addresses:
    - ""
rtc:
    tcp_port: 40781
    port_range_start: 40500
    port_range_end: 40600
    use_external_ip: true
    enable_loopback_candidate: false
redis:
    address: localhost:6379
    username: ""
    password: ""
    db: 0
    use_tls: false
    sentinel_master_name: ""
    sentinel_username: ""
    sentinel_password: ""
    sentinel_addresses: []
    cluster_addresses: []
    max_redirects: null
turn:
    enabled: true
    domain: livekit-turn.domain.name
    tls_port: 5349
    udp_port: 40347
    external_tls: true
keys:
    -: -
```
3.nginx.conf
```
ssl_certificate path/fullchain.pem;
ssl_certificate_key path/privkey.pem;
server {
                listen 443 ssl;
                server_name livekit.domain.name;

                location / {
                        proxy_http_version 1.1;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection "upgrade";
                        proxy_set_header Host $host;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header X-Forwarded-Proto $scheme;
                        proxy_redirect off;
                proxy_pass http://localhost:7880;

            }
        }

        server {
            listen 443 ssl;
            server_name livekit-turn.domain.name;


            location / {
                proxy_http_version 1.1;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection "upgrade";
                        proxy_set_header Host $host;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header X-Forwarded-Proto $scheme;
                        proxy_redirect off;
                proxy_pass http://localhost:5349;
            }
        }
```
4.frpc.toml
```
[https_web]
type = tcp
local_ip = 0.0.0.0
local_port = 443
remote_port = 40443

[livekit-turn-udp]
type = udp
local_ip = 0.0.0.0
local_port = 40347
remote_port = 40347

[livekit-rtc-tcp]
type = tcp
local_ip = 0.0.0.0
local_port = 40781
remote_port = 40781

[range:livekit-rtc-udp]
type = udp
local_ip = 0.0.0.0
local_port = 40500-40600
remote_port = 40500-40600
```
5.restart all services
```
systemctl restart nginx
systemctl restart frpc
docker compose restart
```
6.client_config
![image](https://github.com/user-attachments/assets/bcfe1b4e-1169-45d4-ba07-d9066060da11)
4.dns_config
![image](https://github.com/user-attachments/assets/ab0c3afa-10bd-4db1-8ecb-7b1d719dfb1f)

**Expected behavior**

Can conduct video conferences normally

**Screenshots**
![image](https://github.com/user-attachments/assets/3c5cca13-da78-4df7-9e45-2f54f2fb893e)

**Additional context**
If necessary, I can provide my domain address privately
