### ISSUE TITLE
Setup Livekit

### ISSUE THREAD

**Issue by Tealk** [livekit/livekit#3637]
Hi, I'm trying to set up a server with LiveKit, but unfortunately it doesn't seem to work. No matter if I use the cdn docker container or the "livekit-server --dev" command, the rtc.portICERange is missing every time. The only two ports that are opened are 7880 and 7881.

I am currently using the following setup for testing.

etc/livekit/livekit.yaml 
```
port: 7880
bind_addresses:
    - ""
rtc:
    tcp_port: 7881
    port_range_start: 50000
    port_range_end: 50200
    use_external_ip: true
    enable_loopback_candidate: false
turn:
    enabled: false
    domain: rtc-turn.rollenspiel.chat
    tls_port: 5349
    udp_port: 3478
    external_tls: true
keys:
```

/etc/systemd/system/livekit-server.service                                                    
```
[Unit]
Description=LiveKit Server Container
After=network.target

[Service]
LimitNOFILE=500000
Restart=always
WorkingDirectory=/opt/livekit
ExecStart=livekit-server --config /etc/livekit/livekit.yaml

[Install]
WantedBy=multi-user.target
```
