### ISSUE TITLE
error with ICE candidate: 701 STUN host lookup received error

### ISSUE THREAD

**Issue by AdemFr** [livekit/livekit#3682]
I am trying to set up livekit self hosted in kubernetes and tried to follow the documentation and recommendations closely.
Currently we
* Disable TURN
* Have one livekit pod running on a separate node in a public subnet with publicIPs
* Have a working domain behind an alb load balancer

Connections via the playground (by creating a room token via the CLI) seem to work as expected.

When trying to connect via the https://livekit.io/connection-test I see this

```
[...]
Warning: error with ICE candidate: 701 STUN host lookup received error. stun:global.stun.twilio.com:3478
Warning: error with ICE candidate: 701 STUN host lookup received error. stun:stun.l.google.com:19302
Warning: error with ICE candidate: 701 STUN host lookup received error. stun:stun1.l.google.com:19302

Can connect via TURN
Warning: No TURN servers configured.

[...]
Pass
```

Is this something to be concerned about?

The logs from the livekit server pod:

```
2025-05-27T16:59:44.007Z	INFO	livekit	routing/interfaces.go:173	using single-node routing
2025-05-27T16:59:45.233Z	INFO	livekit	rtcconfig/webrtc_config.go:262	failed to get external ip	{"local": "169.254.170.23", "err": "context canceled"}
2025-05-27T16:59:45.233Z	INFO	livekit	rtcconfig/webrtc_config.go:88	using external IPs	{"ips": ["54.188.191.37/10.20.201.73", "169.254.170.23/169.254.170.23"]}
2025-05-27T16:59:45.234Z	INFO	livekit	service/server.go:258	starting LiveKit server	{"portHttp": 7880, "nodeID": "ND_PXHxC5C8iFQB", "nodeIP": "54.188.191.37", "version": "1.8.3", "rtc.portTCP": 7881, "rtc.portICERange": [50000, 60000]}
[...]
```

This is our `values.yaml`:

```
# Taken from:
# Perma link: https://github.com/livekit/livekit-helm/blob/c558a584d4319c0fbbdee2e3fcb4afd75eed467a/livekit-server/values.yaml
# Non perma link: https://github.com/livekit/livekit-helm/blob/master/livekit-server/values.yaml


# configuration for livekit
# you may specify any config settings that are valid in livekit-server's
# config.yaml: https://github.com/livekit/livekit/blob/master/config-sample.yaml
livekit:
  port: ${LIVEKIT_PORT}
  log_level: info
  rtc:
    tcp_port: ${LIVEKIT_RTC_TCP_PORT}
    port_range_start: ${LIVEKIT_RTC_PORT_RANGE_START}
    port_range_end: ${LIVEKIT_RTC_PORT_RANGE_END}
    use_external_ip: true
  turn:
    enabled: false
  redis:
    {}
    # supports sentinels and cluster, see above
    # address:
    # db: 0
    # username:
    # password:
  # In order to set the api keys when using the key_file parameter configure the storeKeysInSecret block below
  key_file: ${KEYS_FILE_NAME_AND_SECRET_SUBPATH}  # This is where the secret content from the external secret below will be mounted

# Set this option to true if you want to store your API keys in a secret instead of the config file
storeKeysInSecret:
  enabled: true
  existingSecret: ${LIVEKIT_API_SECRET_NAME}  # The content of this secret will be mounted into the key_file above

nameOverride: "livekit-server"
fullnameOverride: ""

loadBalancer:
  type: alb
  servicePort: 80
  annotations:
    alb.ingress.kubernetes.io/ip-address-type: "dualstack"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/group.name: "livekit"
    alb.ingress.kubernetes.io/certificate-arn: "${ACM_CERTIFICATE_ARN}"
  tls:
    - hosts:
        - "${LIVEKIT_DOMAIN}"

turnLoadbalancer:
  enable: true  # Default

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
  # targetMemoryUtilizationPercentage: 80

resources:
  # Due to port restrictions, you can run only one instance of LiveKit per physical
  # node. Because of that, we recommend giving it plenty of resources to work with
  limits:
    cpu: 6000m
    memory: 2048Mi
  requests:
    cpu: 4000m
    memory: 1024Mi

podHostNetwork: true

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values: ["livekit-server"]
          topologyKey: "kubernetes.io/hostname"

```
