### ISSUE TITLE
TURN server authentication using Shared Secret

### ISSUE THREAD

**Issue by bijavix** [livekit/livekit#3695]
Currently the only way to config the TURN servers for clients is authenticating using a fixed username and credential:

```
rtc:
  turn_servers:
    - host: myhost.com
      port: 443
      protocol: tls
      username: ""
      credential: ""
```

Would it be possible to support shared secret authentication? 

Using a shared secret, the service generates a temporary username and credential by combining an expiry timestamp with HMAC-SHA1 hashing using the pre-shared secret.
