### ISSUE TITLE
livekit with traefik, traefik.me and docker-compose

### ISSUE THREAD

**Issue by CaosFR** [livekit/livekit#687]
**Describe the bug**
Hi, I would like to configure Livekit with Traefik, but I dont find a good configuration.
I use traefik.me for have SSL trusted certificates.

**Server**
- Version: 0.15.7
- Environment: VM with Debian 11

**Client**
- SDK: https://foundryvtt.com/packages/avclient-livekit
Test with https://example.livekit.io/ => Unable to connect insecure web socket

**To Reproduce**
1. Fresh install with Quickstart tutorial
2. Generation docker-compose.yaml for livekit
3. docker-compose up
8. connect to ws://livekit.****.****/ => 404 not found

**Expected behavior**
In the log livekit keep starting...
**Screenshots**
```
$ docker-compose up
Recreating livekit ... done
Attaching to livekit
livekit    | 2022-05-20T15:30:27.805Z   INFO    livekit logger/logger.go:26     using single-node routing
livekit    | 2022-05-20T15:30:27.863Z   INFO    livekit logger/logger.go:30     UDP receive buffer is too small for a production set-up {"current": 425984, "suggested": 5000000}
livekit    | 2022-05-20T15:30:27.865Z   INFO    livekit logger/logger.go:26     starting LiveKit server {"addr": ":7880", "nodeID": "ND_RqvixjzM", "nodeIP": "****.****.****.****", "version": "0.15.6", "rtc.portTCP": 7881, "rtc.portUDP": 7882}
```

```
cat docker-compose.yaml
version: '3'

services:
  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml --node-ip ***.***.***.****
    container_name: livekit
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.livekit.entrypoints=web,websecure"
      - "traefik.http.routers.livekit.rule=Host(`livekit.****.****)"
      - "traefik.http.routers.livekit.tls=true"
      - "traefik.http.routers.livekit.tls.domains[0].main=livekit.****.****"
      - "traefik.http.routers.livekit.tls.domains[0].sans=livekit-*.****.****"
      - "traefik.http.services.livekit.loadbalancer.server.port=7880"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
```

```
cat livekit.yaml
port: 7880
rtc:
    udp_port: 7882
    tcp_port: 7881
    use_external_ip: false
keys:
    ****: *****
logging:
    json: false
    level: info
```

**Additional context**
-
node-ip ***.***.***.**** it's a LAN with local DNS.

Thanks

**Comment by avvertix** [comment]
@CaosFR The 404 return seems more related to Traefik not knowing there is a service to route.

I would check the following things as my configuration is not so distant from yours:

- In the https://example.livekit.io/ use https websocket protocol `https://livekit.****.****`. The browser will upgrade it during the handshaking
- Check the Traefik labels, I think the service livekit is defined, but not attached to the router (although this usually lead to 502 gateway timeout errors). I do have something like this in mine:

```yaml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ROUTER_NAME.rule=Host(`livekit.****.****`)"
      - "traefik.http.routers.ROUTER_NAME.entrypoints=websecure"
      - "traefik.http.routers.ROUTER_NAME.tls=true"
      - "traefik.http.routers.ROUTER_NAME.tls.certresolver=mytls"
      - "traefik.http.routers.ROUTER_NAME.service=SERVICE_NAME"
      - "traefik.http.services.SERVICE_NAME.loadbalancer.server.port=7880"
```

- Map the 7881 and 7882 ports so they are accessible from outside

```yaml
    ports:
      - "7881:7881"
      - "7882:7882/udp"
```

This is my full docker-compose.yaml file (of course with sensible values redacted)

```
version: '3.9'

networks:
  internal:
  web:
    external:
      name: reverseproxy_traefik_web


services:

  livekit:
    image: livekit/livekit-server:v0.15.7
    command: --config /etc/livekit.yaml --node-ip ***.***.***.***
    restart: unless-stopped
    networks:
      - internal
      - web
    ports:
      - "7881:7881"
      - "7882:7882/udp"
    depends_on:
      - redis
    volumes:
      - ./configuration/livekit.yaml:/etc/livekit.yaml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.livekit.rule=Host(`livekit.****.****`)"
      - "traefik.http.routers.livekit.entrypoints=websecure"
      - "traefik.http.routers.livekit.tls=true"
      - "traefik.http.routers.livekit.tls.certresolver=mytls"
      - "traefik.http.routers.livekit.service=livekit"
      - "traefik.http.services.livekit.loadbalancer.server.port=7880"

  redis:
    image: redis:6-alpine
    command: redis-server /etc/redis.conf
    networks:
      - internal
    volumes:
      - ./configuration/redis.conf:/etc/redis.conf
```

I also have redis configured, but is like the default that is generated by livekit/generate run, except the fact that instead of localhost I used the name of the livekit service as host.

My Traefik configuration is generated using an Ansible role, here the template it uses
https://github.com/OneOffTech/ansible-role-reverseproxy/blob/traefik-2/templates/traefik.toml.j2 (I'm assuming Traefik v2 based on the labels you are using)
