### ISSUE TITLE
Problems launching; is `livekit.yaml` loading?

### ISSUE THREAD

**Issue by c4lliope** [livekit/livekit#749]
`docker-compose.yml`:
```yaml
services:
  relay:
    ports:
      - 7880:7880
      - 7881:7881
      - 7882:7882/udp
    volumes:
      - ./livekit.yaml:/livekit.yaml
    image: livekit/livekit-server
    command: "/livekit-server --config /livekit.yaml --node-ip 127.0.0.1"
```

`> clear; alias dc='docker-compose'; cat livekit.yaml; echo; dc down -v; dc up`
```
port: 7880
rtc:
    udp_port: 7882
    tcp_port: 7881
    use_external_ip: false
keys:
    <abc123>: <a1b2c3>
logging:
    json: false
    level: info

Removing phoneassembledapp_relay_1 ... done
Removing network phoneassembledapp_default
Creating network "phoneassembledapp_default" with the default driver
Creating phoneassembledapp_relay_1 ... done
Attaching to phoneassembledapp_relay_1
relay_1  | 2022-06-03T20:58:44.868Z     INFO    livekit routing/interfaces.go:101       using single-node routing
relay_1  | one of key-file or keys must be provided in order to support a secure installation
phoneassembledapp_relay_1 exited with code 0
```
