### ISSUE TITLE
Deploying on a GKE cluster - Do I need my nodes to have public ips?

### ISSUE THREAD

**Issue by calexandre** [livekit/livekit#848]
Hey all!

I followed [the guide](https://docs.livekit.io/deploy/kubernetes/) to deploy on the Kubernetes (GKE) and used the helm-chart-values provided [here](https://github.com/livekit/livekit-helm/blob/master/examples/server-gke.yaml).

After the successfully deploying, I ended up with the following exposed resources:
- 1x ingress for reaching livekit api on `https://livekit.something.com` with a public ip and a valid certificate (used letsencrypt)
- 1x loadbalancer exposing TURN on `443` on `https://turn-livekit.something.com` with a public ip and a valid certificate (used letsencrypt)

Tried to run the livekit connection tester, and it connects successfully to the server, but then everything else fails.

I'm fairly new to WebRTC and after searching a lot through livekit's documentation I was unable to find more information about this.

So my questions are: 
- Do my nodes need to have public IPs for this deployment to work?
- If so, how can I deploy livekit on a cluster with private-nodes?

My `livekit.yaml` configuration:

```yaml
replicaCount: 2
livekit:
  keys:
    <redacted-key>: <redacted-token>
  port: 7880
  log_level: info
  rtc:
    use_external_ip: true
    port_range_end: 60000
    port_range_start: 50000
    tcp_port: 7881
  redis:
    address: redis-headless.redis:6379
  turn:
    enabled: true
    domain: turn-livekit.something.com
    tls_port: 3478
    secretName: turn-livekit-tls
    loadBalancerAnnotations:
      external-dns.alpha.kubernetes.io/hostname: turn-livekit.something.com

loadBalancer:
  type: gke
  tls:
    - hosts:
        -  livekit.something.com
      secretName: livekit-tls

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 300m
    memory: 500Mi
```

Below is the livekit connection tester logs:

```
Connecting to signal connection via WebSocket

Connected to server, version 1.1.2.

Establishing WebRTC connection

WARNING: ports need to be open on firewall in order to connect.

ERROR: could not connect after timeout

Can connect via TURN

ERROR: could not connect after timeout

Can publish audio

ERROR: could not connect after timeout

Can publish video

ERROR: could not connect after timeout

Resuming connection after interruption

WARNING: could not connect after timeout

FAIL
```
